### ISSUE TITLE
Service Connection Failure

### ISSUE THREAD

**Issue by konradoo11** [aicell-lab/agent-lens#5]
Error messages:

**Log Output:**
`Connecting to server...
Server connected.
Getting imasfadsfdsdfasfdsad.
Getting Segmentation service...
Error acquiring segmentation service: RemoteError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/hypha/core/workspace.py", line 808, in get_service
    raise IndexError(f"Service not found: {sid} in workspace {workspace}")
IndexError: Service not found: interactive-segmentation in workspace *

Getting microscope control service...
Error: RemoteError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/hypha/core/workspace.py", line 808, in get_service
    raise IndexError(f"Service not found: {sid} in workspace *")
IndexError: Service not found: microscope-control-squid-test in workspace *
`
**Console Output**
`Creating a new connection to  wss://ai.imjoy.io/ws
...
Error during calling method:  Error: Method not found: 345LVToffrWLjVQDqfTFx5/workspace-manager:...
    at RPC._handle_method ...
`

**Possible Causes**

1. Services Are Not Available Anymore:
The required services (interactive-segmentation and microscope-control-squid-test) might not be running or are not registered with the server anymore.
3. Server or Network Issues:
There might be connectivity issues preventing your app from communicating with the server.
5. Server Changes:
The server you're connecting to might have updated, and the services are no longer available at the same location or under the same IDs.

**Comment by konradoo11** [comment]
@cccoolll Do you know anything about this? If the services are inactive or something?

**Comment by cccoolll** [comment]
Hi, @konradoo11, you can see the current method to access the microscope control services via 'hypha-rpc'

[link to my code](https://github.com/cccoolll/agent-lens/blob/b78dfe972d0fdb1effc2d99b45e7187cfbaa1ad5/docs/index.html#L514-L547)
